name: release
on:
  release:
    types: [published]
env:
  CI_XCODE_VER: '/Applications/Xcode_11.7.app/Contents/Developer'
  CI_XCODE_BETA_VER: '/Applications/Xcode_13.0.app/Contents/Developer'

jobs:
  cocoapods:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Update Framework Version
        run: ./Scripts/update_build
        env:
          BUILD_VERSION: ${{ env.TAG }}
      - name: CocoaPods
        run: set -o pipefail && env NSUnbufferedIO=YES pod lib lint --allow-warnings --verbose
      - name: Deploy CocoaPods
        run: set -o pipefail && env NSUnbufferedIO=YES pod trunk push ParseSwift.podspec --allow-warnings --verbose
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

  docs:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Build
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild docbuild | xcpretty
        env:
          DEVELOPER_DIR: ${{ env.CI_XCODE_BETA_VER }}
          BUILD_VERSION: ${{ env.TAG }}
      - name: Copy files
        run: |
          DOCDIR=$(find build -type d -name '*.doccarchive')
          mkdir -p docs/api
          cp -rf "${DOCDIR}/" docs/api
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
